### ISSUE TITLE
live train status

### ISSUE THREAD

**Issue by prinzpiuz** [prinzpiuz/RailwayStatusBot#4]
refer railwayapi.com to get api format for live train status

**Comment by geetesh-gupta** [comment]
What I have to do? Should I provide the api url here?

**Comment by drowolath** [comment]
Hi there ! Can I assume that what you need is a function that retrieves the live status of a given train ?

**Comment by prinzpiuz** [comment]
> Hi there ! Can I assume that what you need is a function that retrieves the live status of a given train ?

yes ....like the api can be available from railwayapi.com ...you need parse that json response like i did in another commands 
-so you need to add command 
-function for handling that command

**Comment by prinzpiuz** [comment]
> What I have to do? Should I provide the api url here?

just add command and make a function to handle that command like it will parse the json response from api and display in a nice way
